services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_DATABASE: algafoods
      MYSQL_USER: algafoods
      MYSQL_PASSWORD: algafoods
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: algafoods_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/algafoods?allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: algafoods
      SPRING_DATASOURCE_PASSWORD: algafoods
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db
    restart: always

volumes:
  db_data: